//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTA_Manager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTA_Manager.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string buttonAdd {
            get {
                return ResourceManager.GetString("buttonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string buttonBrowse {
            get {
                return ResourceManager.GetString("buttonBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string buttonOpen {
            get {
                return ResourceManager.GetString("buttonOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string buttonPlay {
            get {
                return ResourceManager.GetString("buttonPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string buttonRemove {
            get {
                return ResourceManager.GetString("buttonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Mode.
        /// </summary>
        internal static string comboBoxOffline {
            get {
                return ResourceManager.GetString("comboBoxOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Mode.
        /// </summary>
        internal static string comboBoxOnline {
            get {
                return ResourceManager.GetString("comboBoxOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled Scripts.
        /// </summary>
        internal static string labelDisabled {
            get {
                return ResourceManager.GetString("labelDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled Scripts.
        /// </summary>
        internal static string labelEnabled {
            get {
                return ResourceManager.GetString("labelEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot make changes while GTA V is running..
        /// </summary>
        internal static string MessageChanges {
            get {
                return ResourceManager.GetString("MessageChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot close launcher while GTA V is running..
        /// </summary>
        internal static string MessageClose {
            get {
                return ResourceManager.GetString("MessageClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rage not found! Make sure it is installed correctly.
        /// </summary>
        internal static string MessageRage {
            get {
                return ResourceManager.GetString("MessageRage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove selected scripts?.
        /// </summary>
        internal static string MessageRemove {
            get {
                return ResourceManager.GetString("MessageRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will not take effect until next launch..
        /// </summary>
        internal static string MessageRestart {
            get {
                return ResourceManager.GetString("MessageRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTA V is already running..
        /// </summary>
        internal static string MessageRunning {
            get {
                return ResourceManager.GetString("MessageRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create shortcut to desktop?.
        /// </summary>
        internal static string MessageShortcut {
            get {
                return ResourceManager.GetString("MessageShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTA V not found! Make sure launcher is in GTA V root directory..
        /// </summary>
        internal static string textBoxDirectory {
            get {
                return ResourceManager.GetString("textBoxDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rage not found!.
        /// </summary>
        internal static string TitleRage {
            get {
                return ResourceManager.GetString("TitleRage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string TitleRemove {
            get {
                return ResourceManager.GetString("TitleRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart required.
        /// </summary>
        internal static string TitleRestart {
            get {
                return ResourceManager.GetString("TitleRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTA V is running!.
        /// </summary>
        internal static string TitleRunning {
            get {
                return ResourceManager.GetString("TitleRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create shortcut?.
        /// </summary>
        internal static string TitleShortcut {
            get {
                return ResourceManager.GetString("TitleShortcut", resourceCulture);
            }
        }
    }
}
